#!/bin/bash
echo "whats your name?"
read name 

sleep 3


echo "Hello ,Good Morning $name"

sleep 4


echo "You're looking good today $name"


sleep 5



echo "$name ,What do you wanna have for breakfast today ?" 


sleep 3


echo "sorry $name. that's not available .Choose something else"


sleep 4


echo "Okay $name .Have a great day ahead"
